create table atividades (
        id bigint generated by default as identity,
        atividade varchar(255) not null,
        data date not null,
        hora_fim time(6) not null,
        hora_inicio time(6) not null,
        id_cliente bigint not null,
        observacao varchar(255) not null,
        projeto varchar(255) not null,
        primary key (id)
    );