
    create table clientes (
        id bigint generated by default as identity,
        cnpj varchar(255) not null,
        contato varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    );

    alter table if exists clientes 
       drop constraint if exists UK8tpffwedgo0fmjonjwho3l8vt;

    alter table if exists clientes 
       add constraint UK8tpffwedgo0fmjonjwho3l8vt unique (cnpj);
