
    alter table if exists atividades 
       add column usuario_id bigint not null;

    create table usuarios (
        id bigint generated by default as identity,
        email varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    );

    alter table if exists usuarios 
       drop constraint if exists UKkfsp0s1tflm1cwlj8idhqsad0;

    alter table if exists usuarios 
       add constraint UKkfsp0s1tflm1cwlj8idhqsad0 unique (email);
